site_name: Grupo de Pesquisa INTERPOLI
site_url: https://interpoli.github.io/
site_author: Larissa Alves
site_description: Website oficial do laboratório INTERPOLI da Universidade de São Paulo

theme:
  name: material
  language: pt-BR
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro
  features:
    - navigation.tabs        # Menu horizontal bonito no topo
    - search.expand         # Faz a barra de pesquisa ficar aberta e elegante no topo igual ao padrão comercial
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search

extra_css:
  - stylesheets/extra.css

nav:
  - Início: index.md
  - Pesquisadores: pesquisadores.md
  - Canais: canais.md

# ==========================================================================
# CONFIGURAÇÕES EXTRAS UNIFICADAS
# ==========================================================================
extra:
  analytics:
    provider: google
  custom_colors:
    primary: "#1e366a"
  
  social:
    - icon: material/database      # Ícone do CNPq
      link: http://dgp.cnpq.br/dgp/espelhogrupo/5518890102674013
      name: Diretório de Grupos de Pesquisa (CNPq)
    - icon: material/email
      link: https://interpoli.github.io/canais/
      name: Enviar E-mail
    - icon: material/instagram
      link: https://www.instagram.com/interpoliusp/
      name: Instagram

copyright: >-
    <p>© INTERPOLI. Desenvolvido por <a href="https://github.com/alveslars"> ALVES, L.; Larissa Alves.</a></p>
    <p>© 2026 INTERPOLI-USP. Este site e seu conteúdo, salvo indicação em contrário, estão licenciados sob <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">a Creative Commons Atribuição 4.0 Internacional (CC BY 4.0)</a>, permitindo o compartilhamento e a adaptação do material, desde que seja atribuída a devida autoria.</p>
    <br>
    <div style="text-align: center; margin-top: 15px;">
    <a href="https://www.usp.br" target="_blank"><img src="/assets/logo-usp.png" alt="USP" style="display: inline; vertical-align: middle; max-height: 42px; width: auto; margin: 0 15px;"></a>
    <a href="https://www3.eca.usp.br" target="_blank"><img src="/assets/logo-eca.png" alt="ECA USP" style="display: inline; vertical-align: middle; max-height: 42px; width: auto; margin: 0 15px;"></a>
    <a href="https://interpoli.github.io/" target="_blank"><img src="/assets/logo-branco.png" alt="INTERPOLI" style="display: inline; vertical-align: middle; max-height: 95px; width: auto; margin: 0 15px;"></a>
    </div>

