site_name: Grupo de Pesquisa INTERPOLI
site_description: Website oficial do laboratório INTERPOLI.

theme:
  name: material
  palette:
    # Modo Claro (com o fundo azul-gelo do logo da INTERPOLI)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo      # Azul Marinho no topo
      accent: blue         # Azul dinâmico nos links e detalhes
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    # Modo Escuro (mantido o padrão escuro confortável)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro
  features:
    - navigation.tabs # Menu horizontal bonito no topo
    - navigation.expand # <-- ADICIONE APENAS ESTA LINHA PARA DEIXAR A TELA LARGA

extra_css:
  - stylesheets/extra.css   # Link para o arquivo de cor de fundo que vamos criar agora

nav:
  - Início: index.md
  - Pesquisadores: pesquisadores.md
